# 指定 Docker Compose 项目名称
name: ch2-postgresql

# 定义服务列表
services:
  # Web 服务 - Django 应用
  web:
    # 使用当前目录的 Dockerfile 构建镜像
    build: .
    # 启动容器时执行的命令 - 运行 Django 开发服务器
    command: python /code/manage.py runserver 0.0.0.0:8000
    # 挂载卷 - 将当前目录映射到容器内的 /code 目录，实现代码热更新
    volumes:
      - .:/code
    # 端口映射 - 将主机的 8000 端口映射到容器的 8000 端口
    ports:
      - 8000:8000
    # 依赖关系 - 确保 db 服务先启动
    depends_on:
      - db

  # 数据库服务 - PostgreSQL
  db:
    # 使用官方 PostgreSQL 14 镜像
    image: postgres:14
    # 挂载卷 - 将 postgres_data 卷挂载到容器的数据目录，确保数据持久化
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # 环境变量设置
    environment:
      # 设置身份验证方法为 trust，允许无密码连接（仅适用于开发环境）
      - "POSTGRES_HOST_AUTH_METHOD=trust"

# 定义卷 - 用于持久化存储数据
volumes:
  # postgres_data 卷用于存储 PostgreSQL 数据，确保容器重启后数据不丢失
  postgres_data: