# 项目名称：用于标识 Docker Compose 项目，影响网络名称和容器前缀
name: hello-django

# === 服务定义 ===
services:
  # web 服务：定义 Django 应用的 Web 服务容器
  web:
    # 构建配置：使用当前目录的 Dockerfile 构建自定义镜像
    # 这将执行 Dockerfile 中定义的所有步骤来创建镜像
    build: .
    
    # 端口映射配置：将容器内的 8000 端口映射到主机的 8000 端口
    # 格式为 "主机端口:容器端口"，使得可以通过 localhost:8000 访问应用
    ports:
      - "8000:8000"
    
    # 容器启动命令：容器启动时将执行的命令
    # python manage.py runserver 0.0.0.0:8000 启动 Django 开发服务器
    # 0.0.0.0 表示监听所有网络接口，允许从容器外部访问应用
    # 如果使用 127.0.0.1，则只能从容器内部访问
    command: python manage.py runserver 0.0.0.0:8000
    
    # 卷挂载配置：将主机目录挂载到容器内的指定路径
    # "." 表示当前目录（项目根目录），":/code" 表示挂载到容器内的 /code 目录
    # 这实现了代码热更新：在主机上修改代码后，容器内立即可见，无需重启容器
    # 同时保证容器停止后，数据不会丢失
    volumes:
      - .:/code